config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #read
  get "/tasks", to: "tasks#index"
  #create
  get "tasks/new", to: "tasks#new", as: :new
  post "/tasks", to: "tasks#create"
  get "/tasks/:id", to: "tasks#show", as: :task
  #update
  get "/tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "/tasks/:id", to: "tasks#update", as: :save
  #delete
  delete "/tasks/:id", to: "tasks#destroy", as: :destroy

  #shortcut for all the above
  # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.label :completed %>
  <%= t.text_field :completed %>

  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks:</h1>

<% @tasks.each do |task| %>
  <ul class="list-group">
    <li class="list-inline list-group-item">
      <% if task.completed %>
        <i class="far fa-check-square"></i> <%= link_to task.title, task_path(task) %> <br>
      <% else %>
        <i class="far fa-square"></i> <%= link_to task.title, task_path(task) %> <br>
      <% end %>
    </li>
  </ul>
<% end %>

<br>
<br>
<br>
<%= link_to 'new task', new_path, class: "btn btn-info"%>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<p><%= @task.details %></p>



 <% if @task.completed %>
  <p><i class="far fa-check-square"></i> This task is completed</p>
  <% else %>
  <p><i class="far fa-square"></i> This task is not completed yet</p>
  <% end %>


<%= link_to "back to tasks", tasks_path %>
<%= link_to "edit", task_edit_path %>


<%= link_to "Delete", destroy_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>